// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htmawspfxydhacnuplma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0bWF3c3BmeHlkaGFjbnVwbG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDc4NTI4MDYsImV4cCI6MjAyMzQyODgwNn0.JZXlyoNkP_-yF_DPa_-3MwBf6L_VxHHnYzOJqKYXqxk";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);